// Static Content
export const STORE_TEST_INFO = "STORE_TEST_INFO";
export const STORE_BULK_STATIC_CONTENT = "STORE_BULK_STATIC_CONTENT";

// Redux
export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const CLEAR = "CLEAR";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_MODAL_TITLE = "UPDATE_MODAL_TITLE";

// Authentication
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const STORE_KEYCLOAK_DATA = "STORE_KEYCLOAK_DATA";
export const STORE_USER_ACCESS_DATA = "STORE_USER_ACCESS_DATA";
export const LOGOUT = "LOGOUT";
export const STORE_IS_PROPONENT = "STORE_IS_PROPONENT";

// OrgBook
export const STORE_ORGBOOK_SEARCH_RESULTS = "STORE_ORGBOOK_SEARCH_RESULTS";
export const STORE_ORGBOOK_CREDENTIAL = "STORE_ORGBOOK_CREDENTIAL";
