// Authentication
export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";
export const GET_USER_INFO = "GET_USER_INFO";

// Misc
export const STATIC_CONTENT = "STATIC_CONTENT";
export const LOAD_ALL_STATIC_CONTENT = "LOAD_ALL_STATIC_CONTENT";
export const MODAL = "MODAL";

// OrgBook
export const ORGBOOK = "ORGBOOK";
export const ORGBOOK_SEARCH = "ORGBOOK_SEARCH";
export const ORGBOOK_CREDENTIAL = "ORGBOOK_CREDENTIAL";
